### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ezani92** [ConsoleTVs/Invoices#11]
After i run on the terminal. i still cant use the package.

**Comment by ConsoleTVs** [comment]
What? If u install it using composer everything goes well ^^

**Comment by ezani92** [comment]
Class 'App\Http\Controllers\ConsoleTVs\Invoices\Classes\Invoice' not found

**Comment by hiren004** [comment]
I am also facing same issue after installing package. I have just install using `composer require consoletvs/invoices` and use sample code as you provided. After adding that code i got `Class 'App\Http\Controllers\ConsoleTVs\Invoices\Classes\Invoice' not found` Any help would be great!

I have uses this code anyway:

```
$invoice = ConsoleTVs\Invoices\Classes\Invoice::make()
                ->addItem('Test Item', 10.25, 2, 1412)
                ->addItem('Test Item 2', 5, 2, 923)
                ->addItem('Test Item 3', 15.55, 5, 42)
                ->addItem('Test Item 4', 1.25, 1, 923)
                ->addItem('Test Item 5', 3.12, 1, 3142)
                ->addItem('Test Item 6', 6.41, 3, 452)
                ->addItem('Test Item 7', 2.86, 1, 1526)
                ->number(4021)
                ->tax(21)
                ->notes('Lrem ipsum dolor sit amet, consectetur adipiscing elit.')
                ->customer([
                    'name'      => 'Èrik Campobadal Forés',
                    'id'        => '12345678A',
                    'phone'     => '+34 123 456 789',
                    'location'  => 'C / Unknown Street 1st',
                    'zip'       => '08241',
                    'city'      => 'Manresa',
                    'country'   => 'Spain',
                ])
                ->download('demo');
```

Thanks,

**Comment by ConsoleTVs** [comment]
At the import (top of the controller class):

```
use ConsoleTVs\Invoices\Classes\Invoice;
```

Or at your code...

```
$invoice = \ConsoleTVs\Invoices\Classes\Invoice::make()
                ->addItem('Test Item', 10.25, 2, 1412)
                ->addItem('Test Item 2', 5, 2, 923)
                ->addItem('Test Item 3', 15.55, 5, 42)
                ->addItem('Test Item 4', 1.25, 1, 923)
                ->addItem('Test Item 5', 3.12, 1, 3142)
                ->addItem('Test Item 6', 6.41, 3, 452)
                ->addItem('Test Item 7', 2.86, 1, 1526)
                ->number(4021)
                ->tax(21)
                ->notes('Lrem ipsum dolor sit amet, consectetur adipiscing elit.')
                ->customer([
                    'name'      => 'Èrik Campobadal Forés',
                    'id'        => '12345678A',
                    'phone'     => '+34 123 456 789',
                    'location'  => 'C / Unknown Street 1st',
                    'zip'       => '08241',
                    'city'      => 'Manresa',
                    'country'   => 'Spain',
                ])
                ->download('demo');

```

**Comment by hiren004** [comment]
I have used `$invoice = \ConsoleTVs\Invoices\Classes\Invoice::make()`

Now error change to `Call to undefined function ConsoleTVs\Invoices\Classes\bcmul()`.

**Comment by ConsoleTVs** [comment]
https://github.com/ConsoleTVs/Invoices/blob/master/composer.json#L10

As you may see, bcmath is a required extension. You don't have it installed.

**Comment by hiren004** [comment]
I have install it and enable it in my system. Now i have checked and it gives me like:

`No hint path defined for [invoices].`

**Comment by ConsoleTVs** [comment]
You clearly need to register the service provider...

ConsoleTVs\Invoices\InvoicesServiceProvider

What laravel version are you using?

**Comment by hiren004** [comment]
Hi, I have checked and now got this:  

`fopen(/var/www/html/my-project/vendor/dompdf/dompdf/lib/fonts/c47afe5539ba1b2094563d54dce2def7.ufm): failed to open stream: Permission denied`

I know that this is the permission issue. Have you any idea how we can give the permission to this. I have only idea about storage folder

Thanks!

**Comment by hiren004** [comment]
Hi, i have gave the permission like this:   
`sudo chown -R www-data:www-data /path/to/your/project/vendor
`

That will fixed it and Thanks for your help. You just need to improve the doc. I have read [this](https://erik.cat/projects/Invoices/docs/1) docs and there is no any hint to register the provider in `app.php` as in every package it must be compulsory. Hope you will update your docs and it might helps to other users!

Again, big thank you for your helps!

**Comment by hatimox** [comment]
hello @hiren004 yes, I installed using composer, and add the class to the app.php and installed the extension php7.2-bcmath but still getting this error Call to undefined function ConsoleTVs\Invoices\Classes\bcmul().

**Comment by hiren004** [comment]
@hatimox This is some different issue compare to this thread! Please open other issue with new thread.

Hope you got more views in it.

Thanks!

**Comment by hatimox** [comment]
@hiren004 issue fixed i was installing wrong version of bcmath , thanks for your help

**Comment by hiren004** [comment]
@hatimox It's okay no problem. Happy to hear that! :)

Cheers!!

**Comment by ConsoleTVs** [comment]
Great to hear that :)
