### ISSUE TITLE
Possibility to edit invoices

### ISSUE THREAD

**Issue by omdesignz** [ConsoleTVs/Invoices#17]
I'm running a custom invoice generator on an app.

Basically, I'm able to generate invoices, edit them, and also convert quotes to invoices. I want to test drive this package but Im not sure how to edit created invoices...

Any help?

**Comment by ConsoleTVs** [comment]
Invoices are generated on runtime, so if you change the data on the fly, it will be updated next time you download it. simply change the arguments of the function ^^

**Comment by Rav23** [comment]
I see... Let me give it a try.

**Comment by codevio** [comment]
@ConsoleTVs I think we can close this issue. It seems resolved.
