### ISSUE TITLE
How to get two pages in a document

### ISSUE THREAD

**Issue by david-saint** [ConsoleTVs/Invoices#18]
Hi, I was trying to generate pages in the same document, but I don't know how to go about doing this.
I have tried using two make();but it didn't work
is there any fix you can offer

**Comment by ConsoleTVs** [comment]
what do you mean?

**Comment by Dsaint109** [comment]
I am creating an invoice for service provider and customer. I want to send both invoices in a single pdf file.
The single pdf file would now be sent to each of them.

**Comment by ConsoleTVs** [comment]
Well as far at this package do, its not possible, you will need to use somethinf to merge 2 pdfs

**Comment by Dsaint109** [comment]
Are you planning to implement it in the future.

**Comment by ConsoleTVs** [comment]
Hummm not really...

**Comment by halabe15** [comment]
@david-saint you can implement on your own template styles

```
<style>
    .page_break { page-break-before: always; }
</style>
```

and then in body

`  <div class="page_break"></div>`

this will give you and extra page on PDF template

**Comment by codevio** [comment]
@ConsoleTVs I think we can close this issue.
