### ISSUE TITLE
Diacritic problem

### ISSUE THREAD

**Issue by dominik-wbz** [ConsoleTVs/Invoices#19]
Cannot correctly export letters like ěšč, even when the font supports latin extended.
[demo-13.pdf](https://github.com/ConsoleTVs/Invoices/files/1822613/demo-13.pdf)

**Comment by ConsoleTVs** [comment]
PDF render is done using DomPDF, is there a way to render this on dompdf?

**Comment by codevio** [comment]
After investigating, this is really a bug with DomPDF :

- ěšč directly in the template is working fine;
- ěšč while `print_r($invoice->items are fine)`;

So the bug is in the `$pdf->loadHtml` or `$pdf->render`, not with the Invoices library. I think we should close this issue.
