### ISSUE TITLE
Add Items

### ISSUE THREAD

**Issue by chriskivaze** [ConsoleTVs/Invoices#20]
Hi
Can i add items as an object

`$items = Items::where('user_id','10')->pluck('name','qty','price');
$invoice = ConsoleTVs\Invoices\Classes\Invoice::make()->addItems($items)`

**Comment by omaromp2** [comment]
Im having the exact same doubt. 
Can this be done? 
Or could we extract the items from Model? 
thanks in advanced

**Comment by angauber** [comment]
Just remember that `addItem` is a method so you can chain it like so

    $invoice = Invoice::make();

    foreach ($items as $item) {
        $invoice->addItem($item->name, $item->value, $item->qtt, $item->id);
    }
    
    $invoice->download('whatever');

**Comment by ConsoleTVs** [comment]
@angauber Thank you for the kind response but I think @chriskivaze @omaromp2 should first look at PHP rather than starting using libraries and posting questions on them :/
