### ISSUE TITLE
InvoicesServiceProvider 

### ISSUE THREAD

**Issue by libasoles** [ConsoleTVs/Invoices#23]
Hi. InvoicesServiceProvider class doesn't exist at all in the source code. And composer is complaining: 

`Class 'ConsoleTVs\Invoices\InvoicesServiceProvider' not found`

Am I missing something?

**Comment by libasoles** [comment]
Actually, I see a merged PR that deletes that class:

https://github.com/ConsoleTVs/Invoices/commit/cb5f333e7ae35e82e5c71612f3213b34dedca8f2

(?)

**Comment by ConsoleTVs** [comment]
Downgrade to 1.1.3. My bad there.
