### ISSUE TITLE
php artisan vendor:publish did nothing

### ISSUE THREAD

**Issue by leexin** [ConsoleTVs/Invoices#25]
Config file and views are not copied over to project directory after vendor:publish.
Could it be InvoicesServiceProvider file not found in vendor directory?

Using consoletvs/invoices ^1.2

**Comment by ConsoleTVs** [comment]
https://github.com/ConsoleTVs/Invoices/blob/master/InvoicesServiceProvider.php#L32

It should publish this ^^

**Comment by codevio** [comment]
@ConsoleTVs I think we can close this issue.
