### ISSUE TITLE
Saving the pdf to a different disk

### ISSUE THREAD

**Issue by edmilsonrobson** [ConsoleTVs/Invoices#26]
The save() method saves it in the default disk in the Storage facade. It would be nice being able to specify which disk you want to save in a project with multiples (e.g Storage::disk('s3')...).

I can send a PR to add an array of options to the save() method to take that in consideration (or any other better suggestions to handle this case).

**Comment by josteph** [comment]
Currently the `generate()` method and `$pdf` instance from the `Invoice` class are both `private`. You can set them to `public` and just:
```
$filename = 'file.pdf';

$invoice = Invoice::make()
                  ...
                  ->generate();

Storage::disk('some_storage')->put($filename, $invoice->pdf->output());
```

This is just a temporary workaround for my case though. Just sharing it here.

**Comment by novelnet** [comment]
I guess a little more elegant without modifying the package:
```
$invoice = \ConsoleTVs\Invoices\Classes\Invoice::make($name = 'Invoice');
$pdf = \ConsoleTVs\Invoices\Classes\PDF::generate($invoice);
\Storage::put($filename = 'invoices/test.pdf',  $pdf->output());
```

**Comment by codevio** [comment]
@ConsoleTVs I think we can close this issue.
