### ISSUE TITLE
Question: Subtotals and page numbers on multi-page invoices

### ISSUE THREAD

**Issue by jsphpl** [ConsoleTVs/Invoices#27]
Quick question: Are multi-page invoices properly handled? I mean, what happens if there is a large number of line items, that don't fit on a single page?

I would expect the following:
- Page number (x out of y) on each page
- Subtotals on top of each page (except on first page, of course)
- Totals only on last page
- Optional header/footer on consecutive pages

Thanks a lot!

**Comment by ConsoleTVs** [comment]
At the moment i will create a new page and that's it. It's hard to handle the PDF stuff. However, subtotals and stuff will he hard to implement due the fact that there's not a limit / page in terms of items. since the item size will be determines by it's description.

However, I'll keep an eye open for this as well. Also, if you wish to contribute the library is very simple and the hard parts are done already!

**Comment by jsphpl** [comment]
Yeah, that's why i'm asking. It's always a pain to handle page breaks when you don't know after how many items the break happens.

Do you know of determining the actual height of an element through dompdf?

**Comment by ConsoleTVs** [comment]
Not that I'm aware of. It's hard to play with diferent scales in a PDF. Also, have you considered creating the page in HTML and further print it? This will allow more customizable options... But this library allows server-side saving for example, so u can send it with emails etc.

**Comment by codevio** [comment]
What's worth doing ?

- Page numbers can be done if we have more than one page.
- I don't think we should have subtotal on each page, there would probably have too much information on each page.
- What are consecutive pages ? What kind of header and footer ? Should not the header and footer be the same on each page ?

**Comment by codevio** [comment]
@ConsoleTVs what are your thoughts ?

**Comment by ConsoleTVs** [comment]
> Page numbers can be done if we have more than one page.

Sure

> I don't think we should have subtotal on each page, there would probably have too much information on each page.

I agree, no subtotals on each page.

> What are consecutive pages ? What kind of header and footer ? Should not the header and footer be the same on each page ?

I think they should, the logo should prevail (and maybe the due date and invoice ID on the right of it as well. However, the rest should just be the remaining items

What do you think?

**Comment by codevio** [comment]
Ok, I agree for the header of the page, gonna work on it.

**Comment by codevio** [comment]
@jsphpl Done on PR #50

**Comment by jsphpl** [comment]
Unfortunately i can't test it right now, as the project where we used this package is no longer active. But many thanks anyway, @codevio!

**Comment by ConsoleTVs** [comment]
@jsphpl There is no worries in that, new features are always welcome, specially when @codevio puts so many effort on it!
