### ISSUE TITLE
Multiple tax rates

### ISSUE THREAD

**Issue by jsphpl** [ConsoleTVs/Invoices#28]
Is the library capable of handling different tax rates for each product? In Germany, we have two rates (7% and 19%) for different kinds of products.

Can i show
- the tax class for each line item on the invoice?
- total tax amount for each class separately?

Thanks in advance!

**Comment by ConsoleTVs** [comment]
At the moment there's only one tax: https://github.com/ConsoleTVs/Invoices/blob/master/Classes/Invoice.php#L53

I would love if you could help me out adding these small bits. The invoice class is really simple and documented!

If not, I'll try to keep an eye for an update on this. Marked as a feature

**Comment by jsphpl** [comment]
Cool, thanks for the quick response! Will look into it as soon as i start using your package. I am currently looking for the best solution and have not chosen yet.

**Comment by codevio** [comment]
@jsphpl 
#41 is a pull request for multiple tax rates.

**Comment by codevio** [comment]
@ConsoleTVs I think we can close this issue.

**Comment by ConsoleTVs** [comment]
True!
