### ISSUE TITLE
invoices due date

### ISSUE THREAD

**Issue by ToeiRei** [ConsoleTVs/Invoices#30]
Is it possible to add a due date for the invoice? (to be paid until)

**Comment by ConsoleTVs** [comment]
It's not there yet. I'll add this as a pending feature

**Comment by ToeiRei** [comment]
I'd do it as a default_due with Carbon -  `date('M dS ,Y',strtotime('+3 months'))` in config as it accepts a ton of options making it as simple as that

**Comment by codevio** [comment]
@ToeiRei @ConsoleTVs 
#40 is a pull request for the due date.

**Comment by codevio** [comment]
@ConsoleTVs I think we can close this issue.
