### ISSUE TITLE
different invoice template for quotes

### ISSUE THREAD

**Issue by ToeiRei** [ConsoleTVs/Invoices#31]
It would be cool to having a few more templates in there for various invoice-like documents.

**Comment by ConsoleTVs** [comment]
You can always modify the default one :) By publishing the views you are able to modify it :)

**Comment by ToeiRei** [comment]
I guess I explained it wrong. If you are doing business, you start with a quote which later on gets converted to an invoice. The quote is basically an invoice with different naming conventions of the fields published but their own quote number and it's 'valid until' instead of 'to be paid until'

**Comment by ConsoleTVs** [comment]
It would be cool if you could perhaps link me some sample documents for me to take a look at. I would be able to do such thing as a feature.

Meanwhile you might get around with adding the valid until or paid until to the comments section of the docs

**Comment by ToeiRei** [comment]
aiming for something like
```
$invoice = ConsoleTVs\Invoices\Classes\Invoice::make()
                ->template('quote')
                ->addItem('Test Item', 10.25, 2, 1412)
                ->addItem('Test Item 2', 5, 2, 923)
  [ .... ]
                ->download('the_quote');
```

whereas template is a blade file somewhere in my project

**Comment by ConsoleTVs** [comment]
So you want the ability to change the template and not only have a single template file to modify. That should be easy. I'll look at it later :)

**Comment by halabe15** [comment]
Yes please! That can make all this stuff easier, I need two templates and by modifying the original one with different variables there are many ifs.. Thank you!

**Comment by ConsoleTVs** [comment]
Ouch, forgot about it. May it be possible for one of u to make a pull request? It should be very easy :)

**Comment by halabe15** [comment]
Done!

**Comment by ConsoleTVs** [comment]
Done in 1.2.0
