### ISSUE TITLE
dompdf is slow as hell

### ISSUE THREAD

**Issue by ToeiRei** [ConsoleTVs/Invoices#32]
The big issue with dompdf is that it is slow as hell on bigger installations and images. Rendering an invoice takes about 30 seconds per page. (Logo and a bootstrap table)

As you are using a single Class file where you do the actual PDF it shouldn't be a big deal adding another generator in there. I'm currently evaluating a few choices to see which ones actually improve speed.

**Comment by ToeiRei** [comment]
I'd suggest mpdf as it's still able to render our blades.

**Comment by ToeiRei** [comment]
Suggesting snappy here as the api is pretty much the same - you should be able to switch by only changing the facades

**Comment by aurawindsurfing** [comment]
Hi! Firstly thanks a lot for sharing the package! Nice and easy for quick start!

I think I have found where the issue is with slow generation. It is due to usage of:

```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
```

basically each time you generate invoice you need to pull in the whole bootstrap.min and that is causing the issues. Try simply disabling it and then you will see how fast it should work. The styles should be hardcoded in html and then it works as expected.

Thanks!

**Comment by ConsoleTVs** [comment]
Yes I agree. This is a good one

**Comment by aurawindsurfing** [comment]
```
* {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }

        h1,h2,h3,h4,h5,h6,p,span,div { 
            font-family: DejaVu Sans; 
            font-size:10px;
            font-weight: normal;
        }

        th,td { 
            font-family: DejaVu Sans; 
            font-size:10px;
        }

        .panel {
            margin-bottom: 20px;
            background-color: #fff;
            border: 1px solid transparent;
            border-radius: 4px;
            -webkit-box-shadow: 0 1px 1px rgba(0,0,0,.05);
            box-shadow: 0 1px 1px rgba(0,0,0,.05);
        }

        .panel-default {
            border-color: #ddd;
        }

        .panel-body {
            padding: 15px;
        }

        table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 0px;
            border-spacing: 0;
            border-collapse: collapse;
            background-color: transparent;
            
        }

        thead  {
            text-align: left;
            display: table-header-group;
            vertical-align: middle;
        }

        th, td  {
            border: 1px solid #ddd;
            padding: 6px;
        }

        .well {
            min-height: 20px;
            padding: 19px;
            margin-bottom: 20px;
            background-color: #f5f5f5;
            border: 1px solid #e3e3e3;
            border-radius: 4px;
            -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.05);
            box-shadow: inset 0 1px 1px rgba(0,0,0,.05);
        }
```

work for me

**Comment by codevio** [comment]
I've made the test on localhost.

With `link` to `bootstrap`, it took 3.84s.
With `css` in `head`, it took 1.46s.

Maybe we should update it to put the css in the `head` section ?

**Comment by ConsoleTVs** [comment]
I totally agree.
I created a branch: https://github.com/ConsoleTVs/Invoices/pull/46 (https://github.com/ConsoleTVs/Invoices/tree/faster-render)

@codevio May you try it if you get the same results on that branch?
