### ISSUE TITLE
Image in cell

### ISSUE THREAD

**Issue by paligiannis** [ConsoleTVs/Invoices#49]
I am testing this amazing plugin and trying to figure out if I can pass a custom argument in addItem method in order to import images in cells. 

Does anyone have implemented that?

**Comment by ConsoleTVs** [comment]
Not that I'm aware of, this seems to be something strange to put in an invoice, is it?

I will mark this as an enhancement, so maybe @codevio wants to take a look at it in his free time.

Also, remember this is open source, you can also contribute if you like to add some cool feature ;)

**Comment by codevio** [comment]
@paligiannis I will look at it! :+1:

**Comment by codevio** [comment]
@paligiannis The only way I see where you can use image is in the beginning of each row, as an image product. Is it okay ?

**Comment by ConsoleTVs** [comment]
@codevio I think this is what he is looking for

**Comment by ConsoleTVs** [comment]
@paligiannis The hard work of @codevio made this release (https://github.com/ConsoleTVs/Invoices/releases/tag/1.5.0) possible and it includes the feature you're looking for. Have fun!
