### ISSUE TITLE
Laravel : impossible to use custom template

### ISSUE THREAD

**Issue by marecektn** [ConsoleTVs/Invoices#5]
Great lib, but I've encountered on a problem that putting custom template is impossible since blade lookup only happens within library scope. 
edit: current workaround is to clone PHP class into project and pass to it name of template (since class is in project scope, it works just fine ;)

**Comment by ConsoleTVs** [comment]
Woah, any solution I mifht be able to do? Otherwise I will just delete theoltion to change the template...

The best solution otherwise is to set an option in the invoice to load a custom template rather than modify the actual one.

**Comment by marecektn** [comment]
yea, custom template in invoice is a good solution
thanks for your support!

**Comment by mcharytoniuk** [comment]
@ConsoleTVs please take a look at this PR: https://github.com/ConsoleTVs/Invoices/pull/21

**Comment by hatimox** [comment]
hello @ConsoleTVs how i can use a custom template? also the documentation link is broken if you can update it , thannks

**Comment by halabe15** [comment]
@hatimox you can use a custom template, just update lib

**Comment by codevio** [comment]
@ConsoleTVs I think we can close this issue. It seems resolved.
