### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by ElyGallego** [ConsoleTVs/Invoices#55]
Hi, I tried to upgrade my project to Laravel 7 and wasn't able to do it because ConsoleTVs/Invoices is the only library I'm using that is not compatible with Laravel 7, are you planning on releasing a compatible version any time soon? 
Thanks.

**Comment by ConsoleTVs** [comment]
Can you try 1.6.0 ?

**Comment by ElyGallego** [comment]
It worked, thanks!
