### ISSUE TITLE
error with example

### ISSUE THREAD

**Issue by x0rld** [ConsoleTVs/Invoices#56]
![image](https://user-images.githubusercontent.com/45242856/77924270-c6470400-72a3-11ea-808a-3582118db161.png)
I tried to use your lib who looks easy to use but there is this error

**Comment by ConsoleTVs** [comment]
- Laravel version?
- Invoices version?
- PHP version?
- Lines of code that causes the failing?

**Comment by x0rld** [comment]
I don't use laravel I just wanted to use this to do an invoice in php
it's invoice 1.6
i'm on php 7.4
the error is when the function config() is call 
```php
    public function __construct($name = 'Invoice')
    {
        $this->name = $name;
        $this->template = 'default';
        $this->items = Collection::make([]);
        $this->currency = config('invoices.currency');
        $this->decimals = config('invoices.decimals');
        $this->logo = config('invoices.logo');
        $this->logo_height = config('invoices.logo_height');
        $this->date = Carbon::now();
        $this->business_details = Collection::make(config('invoices.business_details'));
        $this->customer_details = Collection::make([]);
        $this->footnote = config('invoices.footnote');
        $this->tax_rates = config('invoices.tax_rates');
        $this->due_date = config('invoices.due_date') != null ? Carbon::parse(config('invoices.due_date')) : null;
        $this->with_pagination = config('invoices.with_pagination');
        $this->duplicate_header = config('invoices.duplicate_header');
    }```

**Comment by ConsoleTVs** [comment]
As you can see, the construct makes use of the config() helper provided by laravel.

This library was created for laravel, not for the PHP ecosystem itself. You can however, try to create a config() function that takes two parameters and just leave it empty. Maybe this will work...

```
function config($a, $b) {}
```

Next time check out the description :) 

![image](https://user-images.githubusercontent.com/6124435/79048657-dbfee680-7c1e-11ea-90e9-654c1f50fb06.png)

**Comment by RyonMB** [comment]
Hello! I upgraded as well to 1.6 and I am on laravel. Is there changes in how to set tax. Because I got the same error. I previously used ->tax() but I cant use it anymore. I am at laravel 7.*

**Comment by RyonMB** [comment]
I am getting this error 🧨 Method Illuminate\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException: Too few arguments to function ConsoleTVs\Invoices\Classes\Invoice::taxPriceFormatted(), 0 passed in
