### ISSUE TITLE
totalPrice is calculated from string version of subTotalPrice

### ISSUE THREAD

**Issue by marecektn** [ConsoleTVs/Invoices#6]
When using different decimal separators (like , or .) sometimes tax and total sum is calculated to zero.
This issue only occurs when subTotalPrice is over 1000 thus using format_number that adds , after thousands (1,234.00)

This is string is used for calculating total price, which ends up to be 0.

**Comment by ConsoleTVs** [comment]
CN you paste a code to reproduce it?

Thanks!!

**Comment by marecektn** [comment]
made pull request
https://github.com/ConsoleTVs/Invoices/pull/7

**Comment by ConsoleTVs** [comment]
Perfect!
