### ISSUE TITLE
Use the app name by default for the company name

### ISSUE THREAD

**Issue by khalyomede** [ConsoleTVs/Invoices#64]
## Description

Without publishing configuration files, the company name should be the app name (which might be the most handy for a vast majority of monocompany web apps).

## Expected behavior

The `business_details.name` value should use by default `config("app.name")`.

## Actual behavior

The company name is by default "My Company".

**Comment by ConsoleTVs** [comment]
I just made this change: https://github.com/ConsoleTVs/Invoices/blob/master/Config/invoices.php#L60
