### ISSUE TITLE
Add a packagist requirements to have the bcmath extension installed

### ISSUE THREAD

**Issue by khalyomede** [ConsoleTVs/Invoices#65]
## Description

I tried to used the package in a minimal PHP environnement, without compiling it with the bcmath extension. An error has been raised telling me that `bcmul` function does not exists. After downloading the bcmath extension, no error was raised.

## Expected behavior

To be warned if the local environment does not have the required bcmath extension.

## Actual behavior

No error is raised if the local environment does not have the bcmath extension enabled.

**Comment by ConsoleTVs** [comment]
Should't that happen already?

https://github.com/ConsoleTVs/Invoices/blob/master/composer.json#L10

**Comment by khalyomede** [comment]
You absolutely right, I used my local composer binary instead of the composer binary on my Docker container!
